from ev3dev2.motor import OUTPUT_B, OUTPUT_C

CONFIG_FILE = 'config.ini'
LOG_FILE_NAME = 'logs/debug.log'

ROBOT_NAME = 'Eva'

TIME_INTERVAL_BETWEEN_ATTEMPTS = 0.0

LOW_VELOCITY_IN_PERCENT = 10
TEST_VELOCITY_IN_PERCENT = 25
NORMAL_VELOCITY_IN_PERCENT = 50
HIGH_VELOCITY_IN_PERCENT = 80
MAX_VELOCITY_IN_PERCENT = 80


class MotorsPortMapping:
    LEFT_MOTOR = OUTPUT_C
    RIGHT_MOTOR = OUTPUT_B
